/** Fields employees may fill via the self-service data collection link (blank only). */
export const EMPLOYEE_SELF_SERVICE_FIELDS = [
  'nameAsPerAadhar',
  'nameAsPerAadharColumn',
  'dateOfBirth',
  'gender',
  'maritalStatus',
  'fatherName',
  'husbandName',
  'presentAddress',
  'permanentAddress',
  'aadharNo',
  'aadharLinkMobNo',
  'panNo',
  'nameAsPerPan',
  'bankAccountNo',
  'ifscCode',
  'nameAsPerBank',
  'uan',
  'previousUanNo',
  'previousEsicNo',
  'employeeMobile',
  'nomineeName',
  'nomineeDob',
  'nomineeRelation',
  'nomineeMobile',
  'familyMember1Name',
  'familyMember1Dob',
  'familyMember1Relation',
  'familyMember1Mobile',
  'familyMember2Name',
  'familyMember2Dob',
  'familyMember2Relation',
  'familyMember2Mobile',
  'familyMember3Name',
  'familyMember3Dob',
  'familyMember3Relation',
  'familyMember3Mobile',
] as const;

export type EmployeeSelfServiceField = (typeof EMPLOYEE_SELF_SERVICE_FIELDS)[number];

export const REQUIRED_DOCUMENT_LABELS = [
  'PAN Card',
  'Aadhaar Card',
  'Bank Passbook',
  'Bank Statement',
  'Address Proof',
] as const;

export const PASSPORT_PHOTO_LABEL = 'Passport Photo (ID Card)';

/** Unused links expire after 2 days. */
export const DATA_GATHER_LINK_TTL_MS = 2 * 24 * 60 * 60 * 1000;
export const DATA_GATHER_SESSION_TTL_MS = 2 * 60 * 60 * 1000;

export const EMPLOYEE_FIELD_LABELS: Record<EmployeeSelfServiceField, string> = {
  nameAsPerAadhar: 'Employee Name (as per Aadhaar)',
  nameAsPerAadharColumn: 'Name as per Aadhaar',
  dateOfBirth: 'Date of Birth',
  gender: 'Gender',
  maritalStatus: 'Marital Status',
  fatherName: "Father's Name",
  husbandName: "Husband's Name",
  presentAddress: 'Present Address',
  permanentAddress: 'Permanent Address',
  aadharNo: 'Aadhaar Number',
  aadharLinkMobNo: 'Aadhaar-linked Mobile',
  panNo: 'PAN Number',
  nameAsPerPan: 'Name as per PAN',
  bankAccountNo: 'Bank Account Number',
  ifscCode: 'IFSC Code',
  nameAsPerBank: 'Name as per Bank',
  uan: 'UAN',
  previousUanNo: 'Previous UAN',
  previousEsicNo: 'Previous ESIC Number',
  employeeMobile: 'Employee Mobile',
  nomineeName: 'Nominee Name',
  nomineeDob: 'Nominee Date of Birth',
  nomineeRelation: 'Nominee Relation',
  nomineeMobile: 'Nominee Mobile',
  familyMember1Name: 'Family Member 1 Name',
  familyMember1Dob: 'Family Member 1 DOB',
  familyMember1Relation: 'Family Member 1 Relation',
  familyMember1Mobile: 'Family Member 1 Mobile',
  familyMember2Name: 'Family Member 2 Name',
  familyMember2Dob: 'Family Member 2 DOB',
  familyMember2Relation: 'Family Member 2 Relation',
  familyMember2Mobile: 'Family Member 2 Mobile',
  familyMember3Name: 'Family Member 3 Name',
  familyMember3Dob: 'Family Member 3 DOB',
  familyMember3Relation: 'Family Member 3 Relation',
  familyMember3Mobile: 'Family Member 3 Mobile',
};
