// VPS/manual entry: node server.js
// Hostinger (output dir "dist", entry "server.js"): use dist/server.js generated by npm run build.
process.env.NODE_ENV = process.env.NODE_ENV || 'production';

require('./dist/main');
