import { moduleAccessForPlan } from './saas-modules.constants';
import { featureEntitlementsForPlan } from './platform-features.constants';

export const DEFAULT_TENANT_ID = 'default';

export const PLATFORM_API_PREFIX = 'platform';

export const TRIAL_OPTIONS = [7, 14, 15, 30] as const;

export const DEFAULT_SUBSCRIPTION_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Ideal for small companies — core HR operations',
    maxEmployees: 50,
    priceMonthly: 999,
    priceQuarterly: 2697,
    priceAnnual: 9990,
    currency: 'INR',
    features: [
      'Employee Management',
      'Attendance',
      'Leave',
      'Employee Self Service',
      'Mobile App',
      'Basic Reports',
      'Email Notifications',
    ],
    moduleAccess: moduleAccessForPlan('starter'),
    featureEntitlements: featureEntitlementsForPlan('starter'),
    maxBranches: 1,
    maxDepartments: 10,
    storageLimitMb: 512,
    apiLimitPerMonth: 1000,
    maxAdminUsers: 2,
    maxMobileUsers: 50,
    priceHalfYearly: 5394,
    priceLifetime: 0,
    active: true,
    sortOrder: 1,
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'For growing organizations with payroll and field ops',
    maxEmployees: 250,
    priceMonthly: 4999,
    priceQuarterly: 13497,
    priceAnnual: 49990,
    currency: 'INR',
    features: [
      'All Starter modules',
      'Payroll',
      'Recruitment',
      'Asset Management',
      'Shift Management',
      'Duty Roster',
      'Mobile App',
      'API Access',
      'Advanced Reports',
      'WhatsApp Notifications',
    ],
    moduleAccess: moduleAccessForPlan('professional'),
    featureEntitlements: featureEntitlementsForPlan('professional'),
    maxBranches: 5,
    maxDepartments: 50,
    storageLimitMb: 2048,
    apiLimitPerMonth: 10000,
    maxAdminUsers: 5,
    maxMobileUsers: 250,
    priceHalfYearly: 26997,
    priceLifetime: 0,
    active: true,
    sortOrder: 2,
  },
  {
    id: 'business',
    name: 'Business',
    description: 'For large teams with performance, training, and expenses',
    maxEmployees: 1000,
    priceMonthly: 14999,
    priceQuarterly: 40497,
    priceAnnual: 149990,
    currency: 'INR',
    features: [
      'All Professional modules',
      'Performance',
      'Training',
      'Expenses',
      'Travel',
      'Documents',
      'Workflow Builder',
      'Advanced Analytics',
      'Custom Approval Chains',
      'Custom Roles',
    ],
    moduleAccess: moduleAccessForPlan('business'),
    featureEntitlements: featureEntitlementsForPlan('business'),
    maxBranches: 20,
    maxDepartments: 200,
    storageLimitMb: 10240,
    apiLimitPerMonth: 50000,
    maxAdminUsers: 15,
    maxMobileUsers: 1000,
    priceHalfYearly: 80997,
    priceLifetime: 0,
    active: true,
    sortOrder: 3,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Unlimited scale with white-label and dedicated infrastructure',
    maxEmployees: -1,
    priceMonthly: 0,
    priceQuarterly: 0,
    priceAnnual: 0,
    currency: 'INR',
    features: [
      'All modules',
      'White Label',
      'Custom Domain',
      'Dedicated Database',
      'Dedicated Storage',
      'API Access',
      'Priority Support',
      'SLA Support',
      'SSO',
      'LDAP',
      'Azure AD Integration',
    ],
    moduleAccess: moduleAccessForPlan('enterprise'),
    featureEntitlements: featureEntitlementsForPlan('enterprise'),
    maxBranches: -1,
    maxDepartments: -1,
    storageLimitMb: -1,
    apiLimitPerMonth: -1,
    maxAdminUsers: -1,
    maxMobileUsers: -1,
    priceHalfYearly: 0,
    priceLifetime: 0,
    active: true,
    sortOrder: 4,
  },
] as const;

export const TENANT_SCOPED_COLLECTIONS = [
  'employees',
  'admins',
  'roles',
  'audit_logs',
  'sessions',
  'locations',
  'job_roles',
  'attendance_records',
  'payroll_ledger',
  'helplines',
  'export_templates',
  'bulk_pay_exports',
  'school_works',
  'school_monthly_billings',
  'school_visits',
  'school_partners',
  'school_supervisors',
  'planned_visits',
  'school_districts',
  'school_blocks',
  'employee_change_requests',
  'employee_data_gather_links',
  'employee_documents',
  'supervisor_requests',
  'commitment_diaries',
  'notifications',
  'supervisor_activity_sessions',
  'tenders',
  'contracts',
  'renewals',
  'renewal_documents',
  'bg_dd_records',
  'bg_dd_documents',
  'leave_types',
  'leave_balances',
  'leave_requests',
  'assets',
  'crm_leads',
  'recruitment_jobs',
  'recruitment_applicants',
  'helpdesk_tickets',
  'knowledge_base_articles',
  'payroll_runs',
  'payslips',
  'automation_workflows',
] as const;
