/** Actions the browser may record via POST /audit-logs (export/download events only). */
export const CLIENT_AUDIT_LOG_ACTIONS = new Set([
  'EXPORT_AUDIT_PDF',
  'EXPORT_AUDIT_EXCEL',
  'DOWNLOAD_ATTENDANCE_CSV',
  'DOWNLOAD_ATTENDANCE_PDF',
  'DOWNLOAD_REPORT_CSV',
  'DOWNLOAD_REPORT_EXCEL',
  'DOWNLOAD_REPORT_PDF',
  'DOWNLOAD_SALARY_CSV',
  'DOWNLOAD_SALARY_EXCEL',
  'DOWNLOAD_SALARY_PDF',
  'DOWNLOAD_TEMPLATE',
  'EXPORT_AXIS_BULKPAY',
  'EXPORT_SCHOOL_AXIS_BULKPAY',
  'EXPORT_REGISTRY_CSV',
  'EXPORT_REGISTRY_EXCEL',
  'EXPORT_REGISTRY_PDF',
]);

export const CLIENT_AUDIT_LOG_MAX_TARGET_LENGTH = 4000;
